apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/{{REPO_OWNER}}/{{APP_NAME}}
    newTag: latest

replicas:
  - name: {{APP_NAME}}
    count: 1

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: {{APP_NAME}}
      data:
        EXAMPLE_KEY: "example-value"  # TODO: replace with {{ENV}}-specific config
    target:
      kind: ConfigMap
      name: {{APP_NAME}}
