apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: {{APP_NAME}}
    count: 1

configMapGenerator:
  - name: {{APP_NAME}}
    behavior: merge
    literals: []
    # Add env-specific overrides with: config-ctl.sh add --app {{APP_NAME}} --env {{ENV}} --config KEY=VAL
