apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{REPO_URL}}
    targetRevision: HEAD
    path: kargo
    directory:
      recurse: true
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
